// ISO 4217 currency list for the business-input form. Covers every currency
// with an active circulating use (not historical/replaced codes), so any
// country's applicant can model their study in their own currency.

export interface Currency {
  code: string;
  name: string;
  symbol: string;
}

export const CURRENCIES: Currency[] = [
  { code: "USD", name: "US Dollar", symbol: "$" },
  { code: "EUR", name: "Euro", symbol: "€" },
  { code: "GBP", name: "British Pound", symbol: "£" },
  { code: "JPY", name: "Japanese Yen", symbol: "¥" },
  { code: "CNY", name: "Chinese Yuan", symbol: "¥" },
  { code: "CHF", name: "Swiss Franc", symbol: "CHF" },
  { code: "CAD", name: "Canadian Dollar", symbol: "$" },
  { code: "AUD", name: "Australian Dollar", symbol: "$" },
  { code: "NZD", name: "New Zealand Dollar", symbol: "$" },
  { code: "SEK", name: "Swedish Krona", symbol: "kr" },
  { code: "NOK", name: "Norwegian Krone", symbol: "kr" },
  { code: "DKK", name: "Danish Krone", symbol: "kr" },
  { code: "PLN", name: "Polish Zloty", symbol: "zł" },
  { code: "CZK", name: "Czech Koruna", symbol: "Kč" },
  { code: "HUF", name: "Hungarian Forint", symbol: "Ft" },
  { code: "RON", name: "Romanian Leu", symbol: "lei" },
  { code: "BGN", name: "Bulgarian Lev", symbol: "лв" },
  { code: "HRK", name: "Croatian Kuna", symbol: "kn" },
  { code: "ISK", name: "Icelandic Krona", symbol: "kr" },
  { code: "TRY", name: "Turkish Lira", symbol: "₺" },
  { code: "RUB", name: "Russian Ruble", symbol: "₽" },
  { code: "UAH", name: "Ukrainian Hryvnia", symbol: "₴" },

  // --- MENA (Middle East & North Africa) — high priority for this app ---
  { code: "SAR", name: "Saudi Riyal", symbol: "﷼" },
  { code: "AED", name: "UAE Dirham", symbol: "د.إ" },
  { code: "QAR", name: "Qatari Riyal", symbol: "ر.ق" },
  { code: "KWD", name: "Kuwaiti Dinar", symbol: "د.ك" },
  { code: "BHD", name: "Bahraini Dinar", symbol: ".د.ب" },
  { code: "OMR", name: "Omani Rial", symbol: "ر.ع." },
  { code: "JOD", name: "Jordanian Dinar", symbol: "د.ا" },
  { code: "ILS", name: "Israeli Shekel", symbol: "₪" },
  { code: "EGP", name: "Egyptian Pound", symbol: "ج.م" },
  { code: "TND", name: "Tunisian Dinar", symbol: "د.ت" },
  { code: "DZD", name: "Algerian Dinar", symbol: "د.ج" },
  { code: "MAD", name: "Moroccan Dirham", symbol: "د.م." },
  { code: "LYD", name: "Libyan Dinar", symbol: "ل.د" },
  { code: "LBP", name: "Lebanese Pound", symbol: "ل.ل" },
  { code: "IQD", name: "Iraqi Dinar", symbol: "ع.د" },
  { code: "YER", name: "Yemeni Rial", symbol: "﷼" },
  { code: "SYP", name: "Syrian Pound", symbol: "£S" },
  { code: "SDG", name: "Sudanese Pound", symbol: "ج.س." },
  { code: "MRU", name: "Mauritanian Ouguiya", symbol: "UM" },

  // --- Sub-Saharan Africa ---
  { code: "NGN", name: "Nigerian Naira", symbol: "₦" },
  { code: "ZAR", name: "South African Rand", symbol: "R" },
  { code: "KES", name: "Kenyan Shilling", symbol: "KSh" },
  { code: "GHS", name: "Ghanaian Cedi", symbol: "₵" },
  { code: "ETB", name: "Ethiopian Birr", symbol: "Br" },
  { code: "UGX", name: "Ugandan Shilling", symbol: "USh" },
  { code: "TZS", name: "Tanzanian Shilling", symbol: "TSh" },
  { code: "XOF", name: "West African CFA Franc", symbol: "CFA" },
  { code: "XAF", name: "Central African CFA Franc", symbol: "FCFA" },
  { code: "RWF", name: "Rwandan Franc", symbol: "FRw" },
  { code: "ZMW", name: "Zambian Kwacha", symbol: "ZK" },
  { code: "MZN", name: "Mozambican Metical", symbol: "MT" },
  { code: "BWP", name: "Botswana Pula", symbol: "P" },
  { code: "NAD", name: "Namibian Dollar", symbol: "$" },
  { code: "MUR", name: "Mauritian Rupee", symbol: "₨" },
  { code: "SCR", name: "Seychellois Rupee", symbol: "₨" },
  { code: "AOA", name: "Angolan Kwanza", symbol: "Kz" },
  { code: "CDF", name: "Congolese Franc", symbol: "FC" },
  { code: "SOS", name: "Somali Shilling", symbol: "Sh" },
  { code: "DJF", name: "Djiboutian Franc", symbol: "Fdj" },
  { code: "MWK", name: "Malawian Kwacha", symbol: "MK" },
  { code: "MGA", name: "Malagasy Ariary", symbol: "Ar" },
  { code: "GNF", name: "Guinean Franc", symbol: "FG" },
  { code: "SLL", name: "Sierra Leonean Leone", symbol: "Le" },
  { code: "LRD", name: "Liberian Dollar", symbol: "$" },
  { code: "GMD", name: "Gambian Dalasi", symbol: "D" },
  { code: "CVE", name: "Cape Verdean Escudo", symbol: "$" },
  { code: "BIF", name: "Burundian Franc", symbol: "FBu" },
  { code: "SZL", name: "Eswatini Lilangeni", symbol: "L" },
  { code: "LSL", name: "Lesotho Loti", symbol: "L" },

  // --- Asia-Pacific ---
  { code: "INR", name: "Indian Rupee", symbol: "₹" },
  { code: "PKR", name: "Pakistani Rupee", symbol: "₨" },
  { code: "BDT", name: "Bangladeshi Taka", symbol: "৳" },
  { code: "LKR", name: "Sri Lankan Rupee", symbol: "₨" },
  { code: "NPR", name: "Nepalese Rupee", symbol: "₨" },
  { code: "AFN", name: "Afghan Afghani", symbol: "؋" },
  { code: "KRW", name: "South Korean Won", symbol: "₩" },
  { code: "SGD", name: "Singapore Dollar", symbol: "$" },
  { code: "HKD", name: "Hong Kong Dollar", symbol: "$" },
  { code: "TWD", name: "New Taiwan Dollar", symbol: "$" },
  { code: "MYR", name: "Malaysian Ringgit", symbol: "RM" },
  { code: "THB", name: "Thai Baht", symbol: "฿" },
  { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp" },
  { code: "PHP", name: "Philippine Peso", symbol: "₱" },
  { code: "VND", name: "Vietnamese Dong", symbol: "₫" },
  { code: "MMK", name: "Myanmar Kyat", symbol: "K" },
  { code: "KHR", name: "Cambodian Riel", symbol: "៛" },
  { code: "LAK", name: "Lao Kip", symbol: "₭" },
  { code: "BND", name: "Brunei Dollar", symbol: "$" },
  { code: "MNT", name: "Mongolian Tugrik", symbol: "₮" },
  { code: "KZT", name: "Kazakhstani Tenge", symbol: "₸" },
  { code: "UZS", name: "Uzbekistani Som", symbol: "so'm" },
  { code: "AZN", name: "Azerbaijani Manat", symbol: "₼" },
  { code: "GEL", name: "Georgian Lari", symbol: "₾" },
  { code: "AMD", name: "Armenian Dram", symbol: "֏" },

  // --- Americas ---
  { code: "MXN", name: "Mexican Peso", symbol: "$" },
  { code: "BRL", name: "Brazilian Real", symbol: "R$" },
  { code: "ARS", name: "Argentine Peso", symbol: "$" },
  { code: "CLP", name: "Chilean Peso", symbol: "$" },
  { code: "COP", name: "Colombian Peso", symbol: "$" },
  { code: "PEN", name: "Peruvian Sol", symbol: "S/" },
  { code: "UYU", name: "Uruguayan Peso", symbol: "$" },
  { code: "BOB", name: "Bolivian Boliviano", symbol: "Bs." },
  { code: "PYG", name: "Paraguayan Guarani", symbol: "₲" },
  { code: "VES", name: "Venezuelan Bolivar", symbol: "Bs." },
  { code: "DOP", name: "Dominican Peso", symbol: "RD$" },
  { code: "GTQ", name: "Guatemalan Quetzal", symbol: "Q" },
  { code: "CRC", name: "Costa Rican Colon", symbol: "₡" },
  { code: "PAB", name: "Panamanian Balboa", symbol: "B/." },
  { code: "HNL", name: "Honduran Lempira", symbol: "L" },
  { code: "NIO", name: "Nicaraguan Cordoba", symbol: "C$" },
  { code: "JMD", name: "Jamaican Dollar", symbol: "$" },
  { code: "TTD", name: "Trinidad & Tobago Dollar", symbol: "$" },
  { code: "BSD", name: "Bahamian Dollar", symbol: "$" },
  { code: "BBD", name: "Barbadian Dollar", symbol: "$" },
  { code: "XCD", name: "East Caribbean Dollar", symbol: "$" },

  // --- Europe (non-eurozone, remaining) ---
  { code: "RSD", name: "Serbian Dinar", symbol: "дин." },
  { code: "ALL", name: "Albanian Lek", symbol: "L" },
  { code: "MKD", name: "Macedonian Denar", symbol: "ден" },
  { code: "BAM", name: "Bosnia-Herzegovina Mark", symbol: "KM" },
  { code: "MDL", name: "Moldovan Leu", symbol: "L" },
  { code: "BYN", name: "Belarusian Ruble", symbol: "Br" },

  { code: "OTHER", name: "Other / not listed", symbol: "" },
];

export function currencySymbol(code?: string): string {
  if (!code) return "$";
  return CURRENCIES.find((c) => c.code === code)?.symbol || code;
}
