// Public, no-auth sample report — the trust gap the landing page's teaser
// card couldn't close on its own ("here's a score" isn't the same as "here's
// the actual report you'd get"). Runs the real engine in mock mode at request
// time (never touches a live LLM key or a Firestore doc), so it's always in
// sync with whatever the report renderer actually looks like today.
import Link from "next/link";
import { Mark } from "@/components/Brand";
import { Button } from "@/components/kit";
import { Icon } from "@/components/icons";
import { ReportView } from "@/components/ReportView";
import { runFeasibility } from "@/lib/engine/runFeasibility";
import { OpenAIProvider } from "@/lib/engine/provider";
import { SerpApiProvider } from "@/lib/engine/search";
import type { BusinessInput } from "@/lib/engine/types";

export const dynamic = "force-static";

const SAMPLE_INPUT: BusinessInput = {
  business_idea: "A subscription meal-prep service delivering healthy, locally-sourced dinners to busy professionals",
  target_customer: "Urban working professionals aged 25-45 who value health but lack time to cook",
  location: "Austin, USA",
  problem_solved: "Busy professionals struggle to eat healthy on weeknights and rely on expensive takeout",
  product_service: "Weekly boxes of 5 chef-designed, pre-portioned dinners with 15-minute cook times",
  revenue_model: "Subscription: $89/week for 5 dinners, with tiered plans and add-ons",
  competitors: "HelloFresh, Blue Apron, Factor, local meal-prep kitchens",
  monthly_cost: 42000,
  monthly_revenue: 68000,
  unique_advantage: "Hyper-local sourcing partnerships and 15-minute cook times vs competitors' 30-40 minutes",
  currency: "USD",
};

export default async function SampleReportPage() {
  const result = await runFeasibility(SAMPLE_INPUT, {
    llm: new OpenAIProvider({ mock: true }),
    search: new SerpApiProvider({ mock: true }),
  });

  return (
    <div className="min-h-dvh">
      <header className="sticky top-0 z-40 border-b border-border/70 bg-paper/85 backdrop-blur">
        <div className="mx-auto flex h-16 max-w-4xl items-center justify-between px-5 sm:px-6">
          <Link href="/" className="flex items-center gap-2 font-semibold">
            <Mark className="h-7 w-7" /> FeasibilityAI
          </Link>
          <Button href="/signup" className="text-sm">Analyze my own idea <Icon name="arrow" size={16} /></Button>
        </div>
      </header>

      <div className="mx-auto max-w-4xl space-y-5 px-5 py-8 sm:px-6">
        <div className="flex items-start gap-2.5 rounded-xl border border-brand/25 bg-brand/6 px-4 py-3 text-sm">
          <Icon name="risk" size={16} strokeWidth={2} className="mt-0.5 shrink-0 text-brand" />
          <span className="text-muted">
            <strong className="text-ink">This is a live sample</strong>, generated by the real scoring engine — not a mockup or a screenshot. Every number below comes from the same code that runs your own analysis, so what you're about to run looks exactly like this.
          </span>
        </div>

        <ReportView result={result} />

        <div className="card flex flex-col items-center gap-3 p-8 text-center">
          <h2 className="font-display text-xl font-semibold">Ready to run this on your own idea?</h2>
          <p className="max-w-md text-sm text-muted">Free credits on approval — no card required.</p>
          <Button href="/signup" className="mt-1">Analyze my idea <Icon name="arrow" size={17} /></Button>
        </div>
      </div>
    </div>
  );
}
